name: Build 11ty and css
on:
  push:
    branches:
      - master
      
# Conditional environmental if's      
env:
  UPDATE_NPM: true # false = deploy eleventy , true = update npm

jobs:
  build_deploy_eleventy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Npm Build
        if: env.UPDATE_NPM != 'true'
        run: npm run minify
        
#      - name: Deploy
#        if: env.UPDATE_NPM != 'true'
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          publish_dir: ./dist 
#          publish_branch: gh-pages
#          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Commit changes
        if: env.UPDATE_NPM != 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: woodcock3
          author_email: woodcock3@users.noreply.github.com
          message: "Add docs files"
          add: "docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
      - name: pull request on npm update
        if: env.UPDATE_NPM == 'true'
        uses: woodcock3/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
  
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
